/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { ReceiptAnchor, ReceiptAnchorInterface } from "../ReceiptAnchor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "receiptCount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "anchoredAt",
        type: "uint256",
      },
    ],
    name: "BatchAnchored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "receiptCount",
        type: "uint256",
      },
    ],
    name: "anchorBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
    ],
    name: "getBatchRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506101d08061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c80633acba8ec146100385780636850ab7b14610069575b5f80fd5b61005761004636600461015a565b5f9081526020819052604090205490565b60405190815260200160405180910390f35b61007c610077366004610171565b61007e565b005b5f83815260208190526040902060020154156100d95760405162461bcd60e51b815260206004820152601660248201527518985d18da08185b1c9958591e48185b98da1bdc995960521b604482015260640160405180910390fd5b60408051606080820183528482526020808301858152428486018181525f8a81528085528790209551865591516001860155905160029094019390935583518681529081018590529283019190915284917f1e913e68ce77d254be7f9863bafdd1f77a4c24b12d979efc38690fa1b60dd217910160405180910390a2505050565b5f6020828403121561016a575f80fd5b5035919050565b5f805f60608486031215610183575f80fd5b50508135936020830135935060409092013591905056fea26469706673582212204cd88d5d05fdaa0ac10b816c6a2f66b0b08cd7c0b445f1a05ead9e64bae3de4064736f6c63430008180033";

type ReceiptAnchorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReceiptAnchorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReceiptAnchor__factory extends ContractFactory {
  constructor(...args: ReceiptAnchorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReceiptAnchor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReceiptAnchor__factory {
    return super.connect(runner) as ReceiptAnchor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReceiptAnchorInterface {
    return new Interface(_abi) as ReceiptAnchorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReceiptAnchor {
    return new Contract(address, _abi, runner) as unknown as ReceiptAnchor;
  }
}
