/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ReceiptAnchor } from "./ReceiptAnchor";
export * as factories from "./factories";
export { ReceiptAnchor__factory } from "./factories/ReceiptAnchor__factory";
