/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReceiptAnchorInterface extends Interface {
  getFunction(
    nameOrSignature: "anchorBatch" | "getBatchRoot"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorBatch",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchRoot",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchRoot",
    data: BytesLike
  ): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    merkleRoot: BytesLike,
    receiptCount: BigNumberish,
    anchoredAt: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    merkleRoot: string,
    receiptCount: bigint,
    anchoredAt: bigint
  ];
  export interface OutputObject {
    batchId: string;
    merkleRoot: string;
    receiptCount: bigint;
    anchoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiptAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiptAnchor;
  waitForDeployment(): Promise<this>;

  interface: ReceiptAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorBatch: TypedContractMethod<
    [batchId: BytesLike, merkleRoot: BytesLike, receiptCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBatchRoot: TypedContractMethod<[batchId: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorBatch"
  ): TypedContractMethod<
    [batchId: BytesLike, merkleRoot: BytesLike, receiptCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBatchRoot"
  ): TypedContractMethod<[batchId: BytesLike], [string], "view">;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
  };
}
